# Generated by Django 4.1.3 on 2022-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("checked_out", models.BooleanField(default=False)),
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("book_owner", models.CharField(max_length=100)),
            ],
        ),
    ]
