# Generated by Django 4.1.3 on 2022-11-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
