# Generated by Django 4.1.3 on 2022-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="book_owner",
            field=models.CharField(default="library", max_length=100),
        ),
    ]
