# Generated by Django 4.1.3 on 2022-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_alter_books_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
